services:
  evdealersales.presentation:
    build:
      context: .
      dockerfile: EVDealerSales.Presentation/Dockerfile
    image: evdealersales-presentation:latest
    depends_on:
      - evdealersales.database
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__DefaultConnection=Server=evdealersales.database,1433;Database=EVDealerSalesDb;User Id=sa;Password=StrongPassw0rd123;TrustServerCertificate=True;Encrypt=False;MultipleActiveResultSets=True"
      - "JWT__SecretKey=EVDealerSales_SECRETKEY_SIEUCAPBAOMAT_VAYMACHUADU16KYTU"
      - "JWT__Issuer=EVDealerSales_Issuer"
      - "JWT__Audience=EVDealerSales_Audience"
      - GEMINI_API_KEY=AIzaSyDvLWsOUM4Vb-TyH2FaS8kEFGWc53guJpc
      - Stripe__SecretKey=sk_test_51SFr8fERI6stQTTOPc38vP67e0LQO1wgZ2PK7LkqamHOCkrvgVk4LmwSLZw9jpVHrpyXKjdZtlfPxcACnfNf6php00WK8h9008
      - Stripe__PublishableKey=pk_test_51SFr8fERI6stQTTOeBfsdqNvFIeB6ZKCjTxWHcBsW9OZ1qEvVS1axy7miMKdbXBwee17gjQQxnfpbtmZda4MBNHm00dYqaSEO4
      - AppSettings__BaseUrl=http://localhost:5000
    ports:
      - "5000:5000"
    volumes:
      - ./data/keys:/keys

  evdealersales.database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: evdealersales-sqlserver
    ports:
      - "11433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=StrongPassw0rd123
    volumes:
      - sqlserver-data:/var/opt/mssql

volumes:
  sqlserver-data:
   driver: local
